"""Verify a CI build used the requested Cython release line."""

import re
import sys
from pathlib import Path

import Cython


def main():
    if len(sys.argv) != 2 or not re.fullmatch(r"\d+\.\d+", sys.argv[1]):
        raise SystemExit("Usage: check_cython_generated.py MAJOR.MINOR")

    release_line = sys.argv[1]
    version = Cython.__version__
    if not version.startswith(release_line + "."):
        raise SystemExit(f"Expected Cython {release_line}.x, installed {version}")

    with Path("jnius/jnius.c").open(encoding="utf-8") as generated:
        header = generated.readline().strip()
    if header != f"/* Generated by Cython {version} */":
        raise SystemExit(f"Expected Cython {version} generated C, found {header!r}")

    print(f"Cython {version}: {header}")


if __name__ == "__main__":
    main()
