package:
  name: phyjnius
  version: 1.2.2

source:
  git_url: https://github.com/physion/pyjnius.git
  git_tag: v1.2.2
  #md5: 
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 0
  
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ovation = ovation:main
    #
    # Would create an entry point called ovation that calls ovation.main()


requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - jnius

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/physion/pyjnius
  license: GNU Lesser General Public License Version 3 (LGPLv3)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
